# Generated by Django 4.2.4 on 2023-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "ToDo"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        max_length=25,
                    ),
                ),
                ("due_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
